### ISSUE TITLE
Allocation Dropdown menu diplays all items

### ISSUE THREAD

**Issue by seanhammond** [seanhammond/AgBiz-Logic#157] opened 2015-09-08 18:45 UTC
On Allocate your enterprise information Step 1 of 4.

The frontend dropdown needs to properly display all options and allow the user to add any option to their list of enterprises.

**Comment by layneegilbert** [comment] 2015-10-13 22:53
I confirmed Livestock data, but I ran into some questions and issues with Crops. I'll bring these to the next meeting to discuss before logging them here.

I was unable to test Greenhouse because I was unable to get into Enterprise Allocation for Greenhouse (testing on Chrome). The system kept taking me straight from Business Allocation Step 4 of 4 back to AgBiz Logic Home. I'll re-test and open a separate ticket when I have replicable steps.

**Comment by layneegilbert** [comment] 2015-10-17 02:51
Ticket #172 opened to address data issues in Crops.

No data issues identified in Livestock.

Confirmed with Sean that Greenhouse data has not yet been uploaded. I'll open a separate ticket for that.

Closing this one out.

**Closed by layneegilbert** 2015-10-17 02:51 UTC
Labels: high priority
